// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionSecrets2019
{
    internal sealed partial class Vsix
    {
        public const string Id = "SolutionSecrets2019.4ee3c3b7-0e84-447d-9860-a2a08bb0f43a";
        public const string Name = "Solution Secrets 2019";
        public const string Description = @"This extension allows you to synchronize Visual Studio solution secrets across different development workstations.";
        public const string Language = "en-US";
        public const string Version = "1.1.2";
        public const string Author = "Ernesto Cianciotta";
        public const string Tags = "devops;secrets;secrets management;synchronization;user secrets;";
    }
}
