// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionSecrets2019
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSolutionSecrets2019PkgString = "1874eb76-4070-4b33-aef7-2050d0d5c4f8";
        public static Guid guidSolutionSecrets2019Pkg = new Guid(guidSolutionSecrets2019PkgString);

        public const string guidUIContextString = "c61926d5-e2e0-4c0b-af94-155e4bd79809";
        public static Guid guidUIContext = new Guid(guidUIContextString);

        public const string guidSolutionSecrets2019CmdSetString = "f8563090-794f-4f31-9c42-aeac98516185";
        public static Guid guidSolutionSecrets2019CmdSet = new Guid(guidSolutionSecrets2019CmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int menuidSyncSecrets = 0x1100;
        public const int groupidSyncSecretsActions = 0x1110;
        public const int groupidOtherSecretsActions = 0x1120;
        public const int groupidSyncSecretsConfig = 0x1130;
        public const int groupidSyncSecretsMenu = 0x1200;
        public const int cmdidInitSecrestsSync = 0x0100;
        public const int cmdidPushSecrets = 0x0110;
        public const int cmdidPullSecrets = 0x0120;
        public const int cmdidDeleteSecrets = 0x0130;
    }
}