// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionSecrets2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "SolutionSecrets2022.40dfc992-754a-4117-b27b-8fe61faf15e1";
        public const string Name = "Solution Secrets 2022";
        public const string Description = @"This extension allows you to synchronize Visual Studio solution secrets across different development workstations.";
        public const string Language = "en-US";
        public const string Version = "2.1.0";
        public const string Author = "Ernesto Cianciotta";
        public const string Tags = "devops;secrets;secrets management;synchronization;user secrets;";
    }
}
