// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionSecrets2022
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSolutionSecrets2022PkgString = "a5018249-f989-4a5c-a198-711abae86ef2";
        public static Guid guidSolutionSecrets2022Pkg = new Guid(guidSolutionSecrets2022PkgString);

        public const string guidUIContextString = "c61926d5-e2e0-4c0b-af94-155e4bd79809";
        public static Guid guidUIContext = new Guid(guidUIContextString);

        public const string guidSolutionSecrets2022CmdSetString = "3d86c44c-ecc8-420b-a516-f967a425ead7";
        public static Guid guidSolutionSecrets2022CmdSet = new Guid(guidSolutionSecrets2022CmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidPushSecrets = 0x0100;
        public const int cmdidPullSecrets = 0x0110;
        public const int cmdidDeleteSecrets = 0x0120;
        public const int cmdidConfigureCommand = 0x0130;
        public const int menuidSyncSecrets = 0x1100;
        public const int groupidSyncSecretsActions = 0x1110;
        public const int groupidOtherSecretsActions = 0x1120;
        public const int groupidSyncSecretsConfig = 0x1130;
        public const int groupidSyncSecretsMenu = 0x1200;
    }
}